

CREATE TABLE Pais(
	Id INT NOT NULL IDENTITY(1,1),
	Nome VARCHAR(255) NOT NULL,
	PRIMARY KEY(Id)
)
GO


CREATE TABLE Estado(
	Id INT NOT NULL IDENTITY(1,1)
	, Nome VARCHAR(255) NOT NULL
	, Id_Pais INT NOT NULL
	, PRIMARY KEY (Id)
	, FOREIGN KEY (Id_Pais) REFERENCES Pais(id)
)
GO


CREATE TABLE Cidade(
	Id INT NOT NULL IDENTITY(1,1)
	, NOME VARCHAR(255) NOT NULL
	, Id_Estado INT NOT NULL
	, PRIMARY KEY (Id)
	, FOREIGN KEY (Id_Estado) REFERENCES Estado(Id)
)
GO

